name: OrangeFox Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install git-core bc bison build-essential zip curl wget \
            gcc g++ ccache libncurses5-dev libncurses5 flex gawk make \
            python-is-python3 python3-distutils -y

      - name: Sync OrangeFox
        run: |
          mkdir orangefox && cd orangefox
          repo init -u https://gitlab.com/OrangeFox/sync.git -b fox_11.0 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Clone device tree
        run: |
          cd orangefox
          git clone https://github.com/<your-username>/device_lenovo_tb_x505x.git device/lenovo/tb_x505x

      - name: Build Recovery
        run: |
          cd orangefox
          source build/envsetup.sh
          lunch omni_tb_x505x-eng
          mka recoveryimage -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OrangeFox-recovery
          path: orangefox/out/target/product/tb_x505x/recovery.img
